version: '3.1'

services:
  mysql_dev:
    image: mysql:5.7.35
    
    command: --default-authentication-plugin=mysql_native_password
    
    restart: always

    volumes:
      - ./services/mysql_dev/data:/var/lib/mysql
      - ./services/mysql_dev/log:/var/log/mysql
      - ./services/mysql_dev/config:/etc/mysql

    env_file:
      - .prod.env
    
    ports:
      - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9.7

    restart: always
    
    ports:
      - 8080:80
    
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=mysql_dev
      - PMA_PORT=3306
  
  redis:
    image: "redis:alpine"
    
    hostname: redis

    volumes:
      - ./services/redis/data:/data
    
    restart: always

  mongodb:
    
    image: mongo:latest

    env_file:
      - .prod.env

    ports:
      - 27017:27017

    volumes:
      - ./services/mongodb/database:/data/db
    
    restart: always
  
  pulsar:
    image: apachepulsar/pulsar

    volumes:
      - ./services/pulsar/data:/pulsar/data
    
    command: "bin/pulsar standalone"

    restart: always
  

  market_check:
    build: ./services/scrapers/market_check/csv_parser

    volumes:
      - /services/scrapers/market_check/csv_parser/new_files:/new_files

    restart: always
