version: '3.1'

services:
  mysql_dev:
    image: mysql:5.7.35
    
    command: --default-authentication-plugin=mysql_native_password
    
    restart: always

    volumes:
      - ./services/mysql_dev/data:/var/lib/mysql
      - ./services/mysql_dev/log:/var/log/mysql
      - ./services/mysql_dev/config:/etc/mysql
      - ./files:/files

    env_file:
      - .prod.env
    
    ports:
      - 3310:3306
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9.7

    restart: always
    
    ports:
      - 3311:80
    
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=mysql_dev
      - PMA_PORT=3306
  
  redis:
    image: "redis:alpine"
    
    hostname: redis

    volumes:
      - ./services/redis/data:/data
    ports:
      - 6379:6379
    restart: always

  mongodb:
    
    image: mongo:latest

    env_file:
      - .prod.env

    ports:
      - 27020:27017

    volumes:
      - ./services/mongodb/database:/data/db
    
    restart: always
  
  pulsar:
    build: ./services/pulsar

    volumes:
      - ./services/pulsar/pulsardata:/pulsar/data
    
    restart: always
    
    ports:
      - 6650:6650
      - 8080:8080
    
    command: "bin/pulsar standalone -nss"
  

  mc_csv_parser:
    build: ./services/scrapers/market_check/csv_parser

    volumes:
      - ./services/scrapers/market_check/csv_parser/new_files:/new_files
      - ./services/libs:/libs

    env_file:
      - .prod.env
    
    network_mode : host
  
  media:
    build: ./services/media

    volumes:
      - /var/www/html/files:/files
    ports: 
      - "6001:5000"

    restart: always
  
  transform:
    build: ./services/transform

    volumes:
      - ./services/libs:/libs

    env_file:
      - .prod.env
    
    network_mode : host
    
    restart: always
  
  pre_validation:
    build: ./services/pre_validation

    volumes:
      - ./services/libs:/libs

    env_file:
      - .prod.env

    network_mode : host
    
    restart: always
  
  post_validation:
    build: ./services/post_validation

    volumes:
      - ./services/libs:/libs

    env_file:
      - .prod.env
    
    network_mode : host

    restart: always
  
  make_model_prediction:
    build: ./services/ml/prediction/make_model

    volumes:
      - ./services/libs:/libs

    env_file:
      - .prod.env
    network_mode : host

    restart: always
  
  car_image_prediction:
    build: ./services/ml/prediction/car_image

    volumes:
      - ./services/libs:/libs
      - ./media:/media
      - ./services/ml/prediction/car_image/model:/usr/src/app/model

    env_file:
      - .prod.env

    network_mode : host

    restart: always

  registration_prediction:
    build: ./services/ml/prediction/registration

    volumes:
      - ./services/libs:/libs
      - ./media:/media
      - ./services/ml/prediction/registration/model:/usr/src/app/model

    env_file:
      - .prod.env

    network_mode : host
    
    restart: always
  
  post_calculation:
    build: ./services/post_calculation

    volumes:
      - ./services/libs:/libs

    env_file:
      - .prod.env
    network_mode : host

    restart: always