version: '3.1'

services:
  mysql_db:
    image: mysql:5.7.35
    
    command: --default-authentication-plugin=mysql_native_password
    
    restart: always

    volumes:
      - ./services/mysql/data:/var/lib/mysql
      - ./services/mysql/log:/var/log/mysql
      - ./services/mysql/config:/etc/mysql
      - ./files:/files

    env_file:
      - .prod.env
    
    ports:
      - 3306:3306
    
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9.7

    restart: always
    
    ports:
      - 8080:80
    
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=mysql_db
      - PMA_PORT=3306
    
    volumes:
      - ./services/phpmyadmin/config/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
